Restructure source code and prepare for further development
epfl-lasa/pybullet_robot pull request #1
Opened 2021-01-14 16:06 UTC by domire8

First things first, I did not change any source code, i just restructured the code into packages (controllers, robots, simulation) and adapted small things so it works. Then, I also reformatted with CLion.

I only created this PR so you could give me a feedback if the shell script (setup_pipenv.sh) works and if you can then run the simple test (see README on the feature branch).

I changed the default branch of this repo to 'development' with the motivation to keep the master branch in sync with the original repo as it seems that he is still working and improving it. At a later stage we can then see if we want to have the restructured code and new packages on our master branch. Is that okay for you?

2021-01-14 16:39 UTC, eeberhard requested changes
The restructure seems reasonable, and the use of pipenv pleases me. I don't agree with the setup file though. If it's ok with you I would prefer that you instead put the info in the readme.

I was able to configure the environment with `pipenv install` and run the simple_ctrl_test on both my mac and linux. Really cool!

2021-01-14 16:39 UTC, eeberhard commented on Pipfile
> +matplotlib = "==3.3.3"
You don't normally need to be so strict with exact versions in the Pipfile, since the lock file describes the exact working configuration. Normally major.minor number is enough. But there's also nothing wrong with it at all!

2021-01-14 16:39 UTC, eeberhard commented on setup_pipenv.sh
> +#bin/sh
I don't necessarily agree with this setup script. Rather, the setup procedure should be made clear in the readme to "install python3 and pipenv, and run pipenv install", where you provide this snippet for info. 
My reasoning: 
- Installing things to the user's environment should always be as explicit as possible (e.g. have them do it themselves), rather  than hidden in a script. I want to know what's being added to my bins and paths!
- This tries to install some stuff that i might already have installed, so can be inefficient
- You end up in the shell, which is fine, but "setup" and "runtime" should be distinct
- It's not cross-platform

I think if this is just in the README under a "setup" header and a "usage" header it will be fine.

2021-01-14 16:39 UTC, eeberhard commented on Pipfile
> +
A cool feature of a Pipfile is that you can define shortcuts. If you for example add this here:

```
[scripts]
test = "python demos/simple_ctrl_test.py"
```

The in the terminal you can just do `pipenv run test`. Very useful for launching commands, and it also means you don't have to enter the shell yourself. It's basically `pipenv run [some command]` instead of `pipenv shell && [some command]`

2021-01-14 17:37 UTC, domire8 commented on Pipfile
> +matplotlib = "==3.3.3"
this is actually auto-generated. i can remove the last digit if you prefer

2021-01-14 17:37 UTC, domire8 commented on Pipfile
> +
that is indeed cool, i will add that

2021-01-14 17:38 UTC, domire8 commented on setup_pipenv.sh
> +#bin/sh
thats totally fine for me! your reasoning makes sense too

2021-01-18 07:45 UTC, eeberhard approved these changes

2021-01-18 08:30 UTC, merged